version: '3.7'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 5353:5353/udp
      - 32400:32400/udp
      - 32469:32469/udp
    environment:
      ALLOWED_NETWORKS: 192.168.10.0/24
      TZ: Europe/Stockholm
      PLEX_CLAIM: 12321
      ADVERTISE_IP: https://rojter.tech/plex
      PLEX_UID: 1000
      PLEX_GID: 1000
      VERSION: latest
    hostname: DebianHost
    volumes:
      - /var/dockerdata/plex/config:/config
      - /var/dockerdata/plex/transcode:/transcode
      - /var/dockerdata/certs/rojter.tech:/data/certs
      - /media/MediaShare:/data
      - /media/MediaShare:/media
      - /media/MediaShare/Video/Series:/data/tvshows
      - /media/MediaShare/Video/Movies:/data/movies
